name: Flutter CI

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '11'
    
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Cache Flutter Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          build
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
    
    - run: flutter pub get
    
    - name: Run Tests
      run: flutter test
    
    - run: flutter build apk
    
    - uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/apk/release/*.apk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: "Release v1.0.${{ github.run_number }}"
        body: "Automated release from GitHub Actions"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/apk/release/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
